export const token_admin = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7J2lkVXNlcicgOiAnMjE1MjMxJywgJ2VtYWlsVXNlcicgOiAncm9iaW5zb25oYW5rQGdtYWlsLmNvbScsICdwYXNzd29yZFVzZXInIDogJyQyYSQxMiRpWFBrYU4wRXkuTEZoUExiRGRnMFN1bzA3TUN5RGs5RjRBYUJNQ1lzRVlUVXc2SERldFFEbScsICduYW1lVXNlcicgOiAnUm9iaW5zb24gSGFuaycsICdwaG9uZU51bWJlclVzZXInIDogJzg5MzQ2NzgzMDA1JywgJ2FkZHJlc3NVc2VyJyA6ICdUZXhhcywgVVNBJywgJ3JvbGVVc2VyJyA6ICdBRE1JTid9IiwiaWF0IjoxNjgxMTAzNjU2LCJleHAiOjE2ODExMzI0NTZ9.p9lOT0GmqUp1XSYJc0ymSAJd-p-5Ef9Pt2DqsIKHalU";
export const token_user = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb2JpbnNvbmhhbmtAZ21haWwuY29tIiwiaWF0IjoxNjgwNzc4NDc0LCJleHAiOjE2ODA4MDcyNzR9.i1CoYyeUKqEIsNcZtqarYwNeKJ4SedrkceC2-x9GKqQ";

// export default token_admin;
// export default token_user;